name: ST3RLIGHTS RDP

on: 
  workflow_dispatch:

jobs:
  run-environment:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Deploy Secure Windows Mesh Network
      env:
        TS_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        choco install tailscale --no-progress -y
        
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        
        Start-Service tailscale
        
        tailscale up --authkey="$env:TS_KEY" --accept-routes --unattended
        
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
        net user runneradmin "P@sswordCloudRDP2026!"
        
        Write-Host "=========================================================="
        Write-Host " SYSTEM SECURED BY TAILSCALE ENCRYPTION MESH"
        Write-Host "=========================================================="
        Write-Host "LOGIN USERNAME: runneradmin"
        Write-Host "LOGIN PASSWORD: P@sswordCloudRDP2026!"
        Write-Host "=========================================================="
        
        while ($true) { Start-Sleep -Seconds 60 }
      shell: powershell
